### ISSUE TITLE
autoplay toggle?

### ISSUE THREAD

**Issue by derekvan** [danbee/jekyll-video-tag#1]
When I use this tag, the video autoplays, but I can't figure out how to toggle that behavior in the code. Is there something in this code that could trigger that, or is it a setting I need to adjust elsewhere? Thanks!

**Comment by danbee** [comment]
Hi @derekvan. There's nothing specific about the code that says whether a video will autoplay or not. All we do is embed an `iframe` in a tag in order to render it in a responsive manner. There might be something you can change about the source URL. Can you tell me where you're pulling the video URL from and how?

**Comment by derekvan** [comment]
Thanks for helping out. I'm loading the file locally. Here's the HTML that gets created: I can't figure out how the "autoplay" attribute is being added to the <video> tag.
![screen shot 2016-10-07 at 10 04 34 am](https://cloud.githubusercontent.com/assets/890341/19192984/33daf1c4-8c76-11e6-9dbc-f3605eacd28c.png)

**Comment by derekvan** [comment]
Never mind. It appears that iFrames always autoplay videos. But I was able to use your script as a template to make my own version that spits out HTML5 video tag. Thanks.!
